### ISSUE TITLE
Unable to make a rotating cube 

### ISSUE THREAD

**Issue by oomek** [Hapaxia/SelbaWard#30]
There seems to be some limitation about axes, No matter how hard I try I'm unable to create a rotating 3 face cube.
I theory I should be able to do it by just setting origin z for all faces equal to texture size / 2 and then increment the angles with a 90 degrees offset in X for the 2nd face and in Y for the 3rd face. The faces are floating in random directions instead.

**Comment by oomek** [comment]
I've managed to figure out the angles for 3 faces
```
img1.rotation3d(45, 45, 0)
img2.rotation3d(-45, 45, 0) 
img3.rotation3d(35, -30, -54.5)
```
It seems that for the 3rd face an additional transformation is required. Do you have any idea how to calculate that?

**Comment by oomek** [comment]
![image](https://user-images.githubusercontent.com/2974860/93804510-4e4c0c00-fc3e-11ea-99a0-f60935dddae8.png)

**Comment by Hapaxia** [comment]
I wasn't sure exactly what the problem was that you were describing as you only provided an image of the correct result so I experimented to see what it was that you meant. I found that forming a full cube with Sprite 3D is pretty simple but transforming the cube as a whole isn't as easy.

There are two transformations here. Transforming the cube and transforming each face. Sprite 3D can only transform the face and it does so in a specific order in the axes. If I remember correctly, the matrix was formed by pitch being transformed first and then yaw. It's worth noting that the roll is simply the flat 2D rotation and is applied afterwards on the 2D plane.
Then, when it comes to a cube, these are transformations are no longer sufficient. To transform faces into their initial positions and then transform them again as a cube would require additional transformation.

Remember that Sprite 3D isn't a sprite within 3D space, it's a sprite with 3D rotation. The allowance of a z value for the origin was added as an afterthought.
You would probably notice this if you moved a cube made with Sprite 3D around - the perspective doesn't change.

That said, I've been considering ideas about a new version of Sprite 3D (or a new dawable entirely) that would be fully within 3D space and would also - hopefully - allow usage of Elastic Sprite's shader instead of relying on the Sprite 3D's subdivision to make the texture look "good enough".

**Comment by oomek** [comment]
Hi, thanks for your reply. It's, exactly what i figured out, When I added a full second transformation matrix I was able to rotate the camera around the cube, unfortunately the drawing order of the faces is no longer easy to track with 2 transformations, so I started experimenting with pure opengl in perspective projection + zbuffer instead of relying on sfml transformable in ortho projection, this has it's drawbacks though. I can't wrap my head around how to position and scale the quads in the 3d space while I change the far and near values to have the constant size of quads in pixels and nothing clipped on rotation, or FOV changes

**Comment by Hapaxia** [comment]
Indeed. The fact that once you go into 3D, most people just jump into OpenGL directly and that's the reason I haven't really done the more 'expanded' 3D stuff. Generally, people use OpenGL for 3D - even within SFML - so Sprite 3D / Elastic Sprite tend to be used for effects more that full on 3D. Effects like a fake spinning cube in the Selba Ward demo (it uses only 2 sprites), for example.

As you mentioned, though, OpenGL does tend to take a lot of technical knowledge, especially for 3D. That said, anything made in SFML would probably require a lot of that knowledge to use it...

**Comment by oomek** [comment]
The reason I stumbled across your repo was trying to figure out how in our Attract Mode game launcher I could give a proper dept to game thumbnail/logo cards in the games selector. Now we only skew/pinch with broken perspective in UV mapping. Your class gives more freedom in transformations, but I would also require the ability to position the elements in z axis, or be able to look with a camera at the angle on all the elements. The cube was just a test of the limitations. I'm still thinking if there is even a way of achieving an angled stack of cards with the centre one facing forward, or a  row of cards wrapped around a part of a circle and preserving the screen coordinate system at the same time.

**Comment by Hapaxia** [comment]
For simple "cards", Sprite 3D should be able to handle most tasks, albeit not necessarily accurately represented within 3D space since they don't share that space with others. It looks like you are intending to move multiple cards as if one object; this would be a similar situation to the cube - multiple faces as one object being transformed together.

That said, cards can be done relatively well with Sprite 3D; it's just dependant on your requirement of camera angles.
For example, here's a video showing a short (actual) card animation:
https://www.youtube.com/watch?v=yNSEmSMfbgQ
This was actually done with Spinning Card but would be much simpler to do with Sprite 3D.

**Comment by oomek** [comment]
Yes I've seen that video, it's a very nice effect showing the power of Sprite3d, but you're right I won't be able to achieve what I need without a camera transform. I'm leaning towards doing it all in OpenGL as I'll have no problem with draw priorities with zbuffer enabled, and I would not need tessellation. Just those screen space coordinates in a 3D space are bothering me still.

**Comment by Hapaxia** [comment]
You could calculate the vertices in 3D manually. It would basically be taking into account multiple 3D transforms. Once you have the vertices for each card, you could draw these faces using Elastic Sprite (also in Selba Ward) with perspective interpolation with its corners in the positions you calculated; it automatically draws the texture as if its perspective fits those points.

https://github.com/Hapaxia/SelbaWard/wiki/Elastic-Sprite
![Elastic Sprite with perspective intepolation](http://i.imgur.com/gcg39PI.png)

**Comment by oomek** [comment]
I was considering that as well, but the elastic sprite uses vertex shaders, doesn't it? I won't be able to use it until I strip Attract Mode off of the legacy GLES 1.1 backend

**Comment by Hapaxia** [comment]
Elastic Sprite doesn't use vertex shaders but does use a fragment shader. If you're unable to use fragment shader, yes, Elastic Sprite wouldn't be suitable.
