### ISSUE TITLE
Question: plans to port to SFML 3?

### ISSUE THREAD

**Issue by xparq** [Hapaxia/SelbaWard#33]
I'd be quite eager to use ConsoleScreen and PixelDisplay, but, alas, they rely on the deprecated `sf::PrimitiveType::Quads` (if I remember correctly).

Any plans to migrate to the SFML 3 API?
_(I've ported a small GUI lib and Thor2 already (for my personal use), but kinda have run out of steam for yet some more. :) )_

**Comment by Hapaxia** [comment]
I would certainly be up for migrating to SFML 3, sure. When a concrete user-interface is announced, I'll look into re-making the stuff properly.

Are ConsoleScreen and PixelDisplay a problem already? Are quads deprecated within SFML? They shouldn't be causing errors if they are not. If they are deprecated, the documentation shouldn't be showing them as if they're okay.
Unless... you're using the latest version rather than the latest release, maybe?
Obviously, they're deprecated in OpenGL though so it's best to move into correct practices...

With all that being said, I'll be updating them soon; this should, at least, help with the step towards SFML 3 (or the latest 2.x build if they deprecate them too).

**Comment by eXpl0it3r** [comment]
Quads will be deprecated in SFML 2.6 and removed with SFML 3. 

If you're on the SFML master branch (SFML 3 WIP), then it won't compile, but there may also be other issues.

**Comment by Hapaxia** [comment]
Thanks for the info!

Replacing them in advance of SFML 2.6's release seems like it makes the most sense. This should remove all issues with it including future deprecation and removal. Best to do it now!

**Comment by Hapaxia** [comment]
fixed in b35a133

This replaces all usage of the quads primitive and replaces them with other primitive types.

Will leave issue open as the part about converting to SFML 3 still stands.


Note that ConsoleScreenOld still has the quads usage. This version doesn't get updated and will likely get removed eventually.

**Comment by xparq** [comment]
Fantastic! I've not yet been using those components, but they're high on my wish list, and `Quads` used to be a showstopper, which isn't then any more, thanks!

_(Note that there are going to be various other incompatible changes toward SFML 3, so it's a good thing to keep this issue open, indeed. If I get to finally integrate your bits, I'll be back reporting other compatibility issues if/as I encounter them. FYI, since I have no legacy SFML code to maintain, I've just committed to using the (somewhat unstable) v3 API.)_

**Comment by Hapaxia** [comment]
I have created a new branch, "sfml3", to carry a version that should work with the latest WIP version of SFML 3 (master branch).

I've done some testing with it and SFML 3. Feel free to try out this new branch with SFML 3 to see if it works for you as well and, please, let me know if you have any issues with it or even, indeed, if everything is fine!

**Comment by xparq** [comment]
Great news, thanks! (I've been down some other rabbit holes, but I'll keep it in mind in case I do surface eventually and then dive in here.)

(I'm closing this, as the original question has been more than answered. Thanks again!)
